#!/usr/bin/env sh

apply_logging_config() {
  log_level="${1:-${CONFIG_LOG_LEVEL_DEFAULT_VAL}}"

  export FABASOAD_LOG_CONFIG_TEXT_COLOR="${CONFIG_LOG_TEXT_COLOR_DEFAULT_VAL}"
  export FABASOAD_LOG_CONFIG_DATE_FORMAT="${CONFIG_LOG_DATE_FORMAT_DEFAULT_VAL}"
  export FABASOAD_LOG_CONFIG_OUTPUT_FORMAT="${CONFIG_LOG_OUTPUT_FORMAT_DEFAULT_VAL}"
  export FABASOAD_LOG_CONFIG_HEADER="${CONFIG_LOG_HEADER_DEFAULT_VAL}"

  validate_enum "${CONFIG_LOG_LEVEL_ARG_NAME}" "${log_level}" "${CONFIG_LOG_LEVEL_OPTIONS}"
  export FABASOAD_LOG_CONFIG_LOG_LEVEL="${log_level}"
}
