---
name: Functional Tests

on:
  pull_request:
    paths:
      - .github/workflows/test-logging.yml
      - src/**
      - tests/**
      - .bpkg.lock

defaults:
  run:
    shell: sh

jobs:
  functional-tests:
    name: All
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Run tests
        run: make test
